service:
  model_name: QWEN3_32B
  served_model_name: QWEN3_32B
  model_path: QWEN3_32B
  include_frontend: true
  prefix: 0
  head_node_ip: 0.0.0.0
  port: 8000
k8s:
  name_prefix: dynamo
  k8s_namespace: null
  k8s_image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:0.7.0
  k8s_image_pull_secret: null
  k8s_model_cache: ''
  mode: agg
  router_mode: ''
  is_kv: false
  enable_router: false
  name: dynamo-agg
  k8s_engine_mode: null
  use_engine_cm: false
  prefill_engine_args: /workspace/engine_configs/prefill_config.yaml
  decode_engine_args: /workspace/engine_configs/decode_config.yaml
  agg_engine_args: /workspace/engine_configs/agg_config.yaml
workers:
  prefill_workers: 0
  decode_workers: 0
  agg_workers: 1
  prefill_gpus_per_worker: null
  decode_gpus_per_worker: null
  agg_gpus_per_worker: null
params:
  prefill: {}
  decode: {}
  agg:
    tensor_parallel_size: 8
    pipeline_parallel_size: 1
    data_parallel_size: 1
    moe_tensor_parallel_size: 1
    moe_expert_parallel_size: 1
    max_batch_size: 10
    gemm_quant_mode: fp8_block
    moe_quant_mode: fp8_block
    kvcache_quant_mode: fp8
    fmha_quant_mode: fp8
    comm_quant_mode: half
    memory: 11.903
    kv_cache_dtype: fp8
sla:
  isl: 5000
  osl: 1000
  ttft: 374.954
  tpot: 9.515
ModelConfig:
  prefix: 0
  is_moe: false
  nextn: 0
  nextn_accept_rates:
  - 0.85
  - 0
  - 0
  - 0
  - 0
