agg_QWEN3_32B_h200_sxm_sglang_0.5.1.post1_5000_1000_0_1000.101_30.233:
  mode: patch
  serving_mode: agg
  model_name: QWEN3_32B
  total_gpus: 8
  system_name: h200_sxm
  backend_name: sglang
  backend_version: 0.5.1.post1
  isl: 5000
  osl: 1000
  prefix: 0
  ttft: 1000.101
  tpot: 30.233
  enable_wideep: false
  moe_backend: null
  attention_backend: flashinfer
  profiles: []
  config:
    nextn: 0
    nextn_accept_rates:
    - 0.85
    - 0
    - 0
    - 0
    - 0
    worker_config:
      system_name: h200_sxm
      backend_name: sglang
      backend_version: 0.5.1.post1
      num_gpu_per_worker:
      - 1
      - 2
      - 4
      - 8
      tp_list:
      - 1
      - 2
      - 4
      - 8
      pp_list:
      - 1
      dp_list:
      - 1
      moe_tp_list:
      - 1
      moe_ep_list:
      - 1
      gemm_quant_mode: fp8_block
      moe_quant_mode: fp8_block
      kvcache_quant_mode: fp8
      fmha_quant_mode: fp8
      comm_quant_mode: half
